AllCops:
  Exclude:
    - 'berks-cookbooks/**/*'
    - 'knife.rb'
Style/AccessorMethodName:
  Exclude:
    - 'Rakefile'
    - 'libraries/provider_rightscale_backup.rb'
    - 'test/cookbooks/test-rightscale_backup/libraries/helper.rb'
Style/PredicateName:
  Exclude:
    - 'test/cookbooks/test-rightscale_backup/libraries/helper.rb'
Style/GuardClause:
  Exclude:
    - 'test/cookbooks/test-rightscale_backup/libraries/helper.rb'
Style/IfInsideElse:
  Exclude:
    - 'test/cookbooks/test-rightscale_backup/libraries/helper.rb'
